### ISSUE TITLE
save loading_balancing_loss properly

### ISSUE THREAD

**Issue by gouchangjiang** [stanford-futuredata/megablocks#82]
Hi, in the forward function of ParallelMLP, should we save directly the load_balancing_loss  or a tuple of tokens_per_expert and scores? In other words, should [line 428](https://github.com/stanford-futuredata/megablocks/blob/main/megablocks/layers/moe.py#L428C39-L428C56), `save_load_balancing_loss((tokens_per_expert, scores))`, be replaced by `save_load_balancing_loss(self.load_balancing_loss(tokens_per_expert, scores))`?

**Comment by gouchangjiang** [comment]
By the way, should we use balancing_loss when using megablocks?

**Comment by tgale96** [comment]
Hi! We save the data required to compute the load balancing loss, rather than the load balancing loss itself, so that we can compute the LBL for all layers at once using [batched_load_balaning_loss](https://github.com/stanford-futuredata/megablocks/blob/main/megablocks/layers/moe.py#L30).

And yes, we highly recommending using load balancing losses training MoEs!
